create table if not exists public.insight_repos
(
    id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
    insight_id bigint not null,
    repo_id bigint not null,
    created_at timestamp with time zone default now(),
    deleted_at timestamp without time zone default null,

    full_name character varying(255) collate pg_catalog."default",

    constraint insights_to_repos_pkey primary key (id)
)

tablespace pg_default;
