create table if not exists public.insights
(
    id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
    user_id bigint not null,
    name character varying collate pg_catalog."default" not null,
    is_public boolean default false,
    is_favorite boolean default false,
    short_code character varying collate pg_catalog."default",
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    deleted_at timestamp without time zone default null,
    constraint insights_pkey primary key (id)
)

tablespace pg_default;
