create table if not exists public.insight_repos
(
  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  insight_id bigint not null references public.insights (id) on delete cascade on update cascade,
  repo_id bigint not null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  deleted_at timestamp without time zone default null,

  -- elastic columns
  full_name character varying(255) collate pg_catalog."default" null,

  -- dynamic columns
  constraint insights_repos_pkey primary key (id)
)

tablespace pg_default;

-- indexes
create index if not exists insights_repos_idx_repo_id on public.insight_repos (repo_id);
create index if not exists insights_repos_idx_created_at on public.insight_repos (created_at);
create index if not exists insights_repos_idx_updated_at on public.insight_repos (updated_at);
create index if not exists insights_repos_idx_deleted_at on public.insight_repos (deleted_at);
create index if not exists insights_repos_idx_full_name on public.insight_repos (full_name);
