create table if not exists public.insights
(
  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  user_id bigint not null references public.users (id) on delete cascade on update cascade,
  is_public boolean not null default false,
  is_favorite boolean not null default false,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  deleted_at timestamp without time zone default null,

  -- elastic columns
  name character varying(255) collate pg_catalog."default" not null,
  short_code character varying(50) collate pg_catalog."default" null default null,

  -- dynamic columns
  constraint insights_pkey primary key (id)
)

tablespace pg_default;

-- indexes
create index if not exists insights_idx_is_public on public.insights (is_public);
create index if not exists insights_idx_is_favorite on public.insights (is_favorite);
create index if not exists insights_idx_created_at on public.insights (created_at);
create index if not exists insights_idx_updated_at on public.insights (updated_at);
create index if not exists insights_idx_deleted_at on public.insights (deleted_at);
create index if not exists insights_idx_short_code on public.insights (short_code);
