create table if not exists public.user_repos
(
    id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
    user_id bigint not null,
    repo_id bigint not null,

    created_at timestamp with time zone default now(),

    constraint user_repos_pkey primary key (id)
)

tablespace pg_default;
