create table if not exists public.insights
(
  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  user_id bigint not null references public.users (id) on delete cascade on update cascade,
  is_public boolean not null default false,
  is_favorite boolean not null default false,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  deleted_at timestamp without time zone default null,

  -- elastic columns
  name character varying(255) collate pg_catalog."default" not null,
  short_code character varying(50) collate pg_catalog."default",

  -- dynamic columns
  constraint insights_pkey primary key (id)
)

tablespace pg_default;
