create table if not exists public.contributions
(
  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  repo_id bigint not null references public.repos (id) on delete cascade on update cascade,
  count bigint not null default 0,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  deleted_at timestamp without time zone default null,
  last_merged_at timestamp without time zone not null,

  -- elastic columns
  contributor character varying(255) collate pg_catalog."default",
  url character varying(255) collate pg_catalog."default",

  -- dynamic columns
  constraint contributions_pkey primary key (id),
  constraint contributions_hash unique (contributor, repo_id)
)

tablespace pg_default;

-- indexes
