create table public.user_notifications
(
  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  user_id bigint null references public.users (id) on delete cascade on update cascade,
  from_user_id bigint null references public.users (id) on delete cascade on update cascade,
  created_at timestamp without time zone default now() not null,
  updated_at timestamp without time zone default now() not null,
  deleted_at timestamp without time zone default null,
  notified_at timestamp without time zone default now() not null,

  -- elastic columns
  type character varying(100) collate pg_catalog."default" not null default 'internal-slack',
  message character varying(100) collate pg_catalog."default" not null default '',
  read_at timestamp without time zone default null,
  meta_id character varying(32) collate pg_catalog."default" not null default '',

  -- dynamic columns
  constraint user_notifications_pkey primary key (id)
)

tablespace pg_default;

-- indexes
create index user_notifications_idx_created_at on public.user_notifications (created_at);
create index user_notifications_idx_updated_at on public.user_notifications (updated_at);
create index user_notifications_idx_deleted_at on public.user_notifications (deleted_at);
create index user_notifications_idx_notified_at on public.user_notifications (notified_at);
create index user_notifications_idx_title on public.user_notifications (type);
