create table if not exists public.users_to_users_followers
(
  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  user_id bigint not null references public.users (id) on delete cascade on update cascade,
  following_user_id bigint not null references public.users (id) on delete cascade on update cascade,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  deleted_at timestamp without time zone default null,

  -- dynamic columns
  constraint user_followers_pkey primary key (id),
  constraint user_followers_hash unique (user_id, following_user_id)
)

  tablespace pg_default;

-- indexes
create index if not exists user_followers_idx_created_at on public.users_to_users_followers (created_at);
create index if not exists user_followers_idx_updated_at on public.users_to_users_followers (updated_at);
create index if not exists user_followers_idx_deleted_at on public.users_to_users_followers (deleted_at);
