create table if not exists public.users_to_users_followers
(
	id bigint generated by default as identity,
	user_id bigint not null,
	following_user_id bigint not null,
	created_at timestamp default now() not null,
	updated_at timestamp default now() not null,
	deleted_at timestamp,
	constraint followers_pkey
		primary key (id),
	constraint followers_hash
		unique (user_id, following_user_id),
	foreign key (user_id) references public.users,
	foreign key (following_user_id) references public.users
);

tablespace pg_default;