CREATE TABLE pull_request_reviews (

  -- static columns
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),
  pull_request_id int not null references public.pull_requests(id) on delete cascade on update cascade,

  -- timestamps
  created_at timestamp without time zone not null default now(),
  published_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),

  -- elastic columns
  reviewer_login text default ''::text,
  state text default ''::text,

  -- dynamic columns
  constraint pull_request_reviews_pkey primary key (id)
)

tablespace pg_default;

-- indexes
create index if not exists pull_request_reviewers on public.pull_request_reviews (lower(reviewer_login));
