CREATE TABLE IF NOT EXISTS public.user_organizations
(
    -- static columns
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    organization_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,

    -- dynamic columns
    CONSTRAINT user_organizations_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

-- indexes
create index if not exists user_organizations_idx_user_id on user_organizations (user_id);
create index if not exists user_organizations_idx_organization_id on user_organizations (organization_id);
