-------------------------------------------------------------------------------
-- GitHub teams tracking table
-------------------------------------------------------------------------------
create table if not exists gh_teams (
  id bigint not null generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1 ),

  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  deleted_at timestamp without time zone default null,

  -- Team name and raw slug for team
  name character varying(255) collate default null,
  slug character varying(255) collate default null,

  -- An array of associated team members user ids.
  --
  -- Because we may not have all user ids for all GitHub users, this is an agnostic
  -- table of raw bigints with no foriegn key constraints that we can use
  -- to be a source of truth for a given team
  user_ids bigint[] default '{}'::bigint[] not null
);

-- indexes
create index if not exists gh_teams_idx_id on public.gh_teams (id);
create index if not exists gh_teams_idx_created_at on public.gh_teams (created_at);
create index if not exists gh_teams_idx_updated_at on public.gh_teams (updated_at);
create index if not exists gh_teams_idx_deleted_at on public.gh_teams (deleted_at);
create index if not exists gh_teams_idx_name on public.gh_teams (name);
create index if not exists gh_teams_idx_slug on public.gh_teams (slug);
