-- Table: public.user_repos

-- DROP TABLE IF EXISTS public.user_repos;

CREATE TABLE IF NOT EXISTS public.user_repos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    repo_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_repos_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_repos
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.user_repos TO anon;

GRANT ALL ON TABLE public.user_repos TO authenticated;

GRANT ALL ON TABLE public.user_repos TO postgres;

GRANT ALL ON TABLE public.user_repos TO service_role;

GRANT ALL ON TABLE public.user_repos TO supabase_admin;