-- Table: public.insight_repos

-- DROP TABLE IF EXISTS public.insight_repos;

CREATE TABLE IF NOT EXISTS public.insight_repos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    insight_id bigint NOT NULL,
    repo_id bigint NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp without time zone DEFAULT null,
    CONSTRAINT insights_to_repos_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.insight_repos
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.insight_repos TO anon;

GRANT ALL ON TABLE public.insight_repos TO authenticated;

GRANT ALL ON TABLE public.insight_repos TO postgres;

GRANT ALL ON TABLE public.insight_repos TO service_role;

GRANT ALL ON TABLE public.insight_repos TO supabase_admin;

COMMENT ON TABLE public.insight_repos
    IS 'Insights Repositories';
