-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.users
(
  -- Static columns
  id bigint NOT NULL,
  open_issues bigint NOT NULL DEFAULT 0,
  has_stars_data boolean NOT NULL DEFAULT false,
  is_private boolean NOT NULL DEFAULT false,
  is_open_sauced_member boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  deleted_at timestamp without time zone DEFAULT null,
  is_onboarded boolean NOT NULL DEFAULT false,
  role bigint NOT NULL DEFAULT 10,
  is_waitlisted boolean NOT NULL DEFAULT false,
  email character varying(255) COLLATE pg_catalog."default",
  bio character varying(255) COLLATE pg_catalog."default",
  name character varying(100) COLLATE pg_catalog."default",
  twitter_username character varying(15) COLLATE pg_catalog."default",
  company character varying(50) COLLATE pg_catalog."default",
  location character varying(50) COLLATE pg_catalog."default",
  display_local_time boolean NOT NULL DEFAULT false,

  -- Elastic columns
  login character varying(255) COLLATE pg_catalog."default",

  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_login_key UNIQUE (login)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
  OWNER to postgres;

GRANT ALL ON TABLE public.users TO anon;

GRANT ALL ON TABLE public.users TO authenticated;

GRANT ALL ON TABLE public.users TO postgres;

GRANT ALL ON TABLE public.users TO service_role;
