-- Table: public.insights

-- DROP TABLE IF EXISTS public.insights;

CREATE TABLE IF NOT EXISTS public.insights
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    is_public boolean DEFAULT false,
    is_favorite boolean DEFAULT false,
    short_code character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT insights_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.insights
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.insights TO anon;

GRANT ALL ON TABLE public.insights TO authenticated;

GRANT ALL ON TABLE public.insights TO postgres;

GRANT ALL ON TABLE public.insights TO service_role;

GRANT ALL ON TABLE public.insights TO supabase_admin;

COMMENT ON TABLE public.insights
    IS 'Insight Pages';